version: '3.8'

networks:
  swarm-network:
    external: true
  monitoring:
    driver: overlay
    attachable: true
  proxy-network:
    external: true

volumes:
  prometheus_data:
  grafana_data:
  loki_data:


configs:
  prometheus_config:
    file: ./prometheus/prometheus.yml
  grafana_datasources:
    file: ./grafana/provisioning/datasources/prometheus.yml
  grafana_loki_datasource:
    file: ./grafana/provisioning/datasources/loki.yml
  grafana_dashboards_provider:
    file: ./grafana/provisioning/dashboards/provider.yml
  loki_config:
    file: ./loki/loki.yml
  promtail_config_v3:
    file: ./promtail/promtail.yml
services:

  prometheus:
    image: prom/prometheus:v3.2.1
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    volumes:
      - prometheus_data:/prometheus
    networks:
      - monitoring
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana:11.6.0
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_RENDERING_CONCURRENT_RENDER_LIMIT=4
      - GF_DATAPROXY_TIMEOUT=60
      - GF_DATAPROXY_DIAL_TIMEOUT=10
    volumes:
      - grafana_data:/var/lib/grafana
    configs:
      - source: grafana_datasources
        target: /etc/grafana/provisioning/datasources/prometheus.yml
      - source: grafana_dashboards_provider
        target: /etc/grafana/provisioning/dashboards/provider.yml
      - source: grafana_loki_datasource
        target: /etc/grafana/provisioning/datasources/loki.yml
    networks:
      - monitoring
      - proxy-network
      - swarm-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-network
      - traefik.http.routers.monitoring-grafana.rule=Host(`gf.fitandyou.ru`)
      - traefik.http.routers.monitoring-grafana.entrypoints=websecure
      - traefik.http.routers.monitoring-grafana.tls.certresolver=myresolver
      - traefik.http.routers.monitoring-grafana.service=monitoring-grafana
      - traefik.http.services.monitoring-grafana.loadbalancer.server.port=3000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        order: stop-first
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
      restart_policy:
        condition: on-failure

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    command:
      - '--housekeeping_interval=10s'
      - '--docker_only=true'
      - '--store_container_labels=false'
      - '--disable_metrics=advtcp,cpu_topology,cpuset,hugetlb,memory_numa,percpu,perf_event,process,referenced_memory,resctrl,sched,tcp,udp'
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - monitoring
    deploy:
      mode: global
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M
      restart_policy:
        condition: on-failure

  node_exporter:
    image: prom/node-exporter:v1.9.1
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.netclass.ignored-devices=^(veth|docker|br-|lo).*'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - monitoring
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 32M
      restart_policy:
        condition: on-failure
  loki:
    image: grafana/loki:3.0.0
    command: -config.file=/etc/loki/config.yml
    configs:
      - source: loki_config
        target: /etc/loki/config.yml
    volumes:
      - loki_data:/loki
    networks:
      - monitoring
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
  promtail:
    image: grafana/promtail:3.0.0
    command: -config.file=/etc/promtail/config.yml
    configs:
      - source: promtail_config_v3
        target: /etc/promtail/config.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - monitoring
    deploy:
      mode: global  # на каждой ноде
      resources:
        limits:
          memory: 128M