global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'vps-swarm'

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Метрики контейнеров и сервисов через cAdvisor
  # tasks.<service_name> — Swarm DNS резолвит все реплики/ноды сервиса
  - job_name: 'cadvisor'
    dns_sd_configs:
      - names:
          - 'tasks.cadvisor'
        type: 'A'
        port: 8080
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.+):\d+'
        target_label: instance
        replacement: '$1'

  # Метрики хоста (CPU, RAM, disk, network)
  - job_name: 'node_exporter'
    dns_sd_configs:
      - names:
          - 'tasks.node_exporter'
        type: 'A'
        port: 9100
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.+):\d+'
        target_label: instance
        replacement: '$1'
